export class CartItem {
    public sku: string;
    public quantity = 0;
    public price: number;
    public item_id: any;
    public itemTotal: any;
    public selectedProduct: any;
    public skuBundle: any;
    public isPreorder: any;
    public availabilityFlag: any;
    public has_add_ons: any;
    public add_on_code: any;
    public promotion_details: any;
    public utm_source: any;
    public is_affiliate_ada: any;
    public add_on_label: any;
    public easyPhoneLabel: any;
    public campaign100_days: any;
    public is_campaign_mviva: any;
    public campaign_mviva_message: any;
    public campaign_mviva_url: any;
    public is_telco_day: any;
    public telco_day_message: any;
    public is_easyphone: any;
    public is_broadband: any;
    public billType: any;
    public deviceUpfrontPenalty: any;
    public cobpDeviceUpfrontPenalty: any;
    public lifestylePenalty: any;
}
